class Banker{
  constructor(avail,max,alloc){this.avail=avail.map(Number);this.max=max.map(r=>r.map(Number));this.alloc=alloc.map(r=>r.map(Number));this.P=this.max.length;this.R=this.avail.length;this.need=this.max.map((r,i)=>r.map((x,j)=>x-this.alloc[i][j]));this.trace=[];}
  step(){for(let i=0;i<this.P;i++){if(!this.finish[i]){let ok=true;for(let j=0;j<this.R;j++)if(this.need[i][j]>this.work[j])ok=false;if(ok){for(let j=0;j<this.R;j++)this.work[j]+=this.alloc[i][j];this.finish[i]=true;this.seq.push(i);this.record('P'+i+' finished');return true;}}}this.record('deadlock');return false;}
  run(){this.work=this.avail.slice();this.finish=Array(this.P).fill(false);this.seq=[];this.trace=[];this.record('init');let loops=0;while(this.seq.length<this.P&&loops<100){if(!this.step())break;loops++;}let safe=this.seq.length===this.P;this.record(safe?'safe':'deadlock');return{trace:this.trace,safe,seq:this.seq};}
  record(act){this.trace.push({action:act,work:this.work.slice(),finish:this.finish.slice()});}
}
class Animator{
  constructor(c,stats){this.c=c;this.ctx=c.getContext('2d');this.stats=stats;this.trace=[];this.i=0;}
  setTrace(t){this.trace=t;this.i=0;this.draw();document.getElementById('timeline').max=t.length-1;}
  next(){if(this.i<this.trace.length-1)this.i++;this.draw();}
  prev(){if(this.i>0)this.i--;this.draw();}
  draw(){const s=this.trace[this.i];const ctx=this.ctx;ctx.clearRect(0,0,this.c.width,this.c.height);if(!s)return;ctx.font='14px monospace';ctx.fillStyle='#cfe8ff';ctx.fillText('Step '+this.i+' - '+s.action,20,20);let y=40;ctx.fillText('Work: '+s.work.join(','),20,y);y+=20;ctx.fillText('Finish: '+s.finish.map(x=>x?1:0).join(','),20,y);this.stats.textContent='Step '+this.i+'\nAction: '+s.action+'\nWork: ['+s.work.join(', ')+']';}
}
const numP=document.getElementById('numProc'),numR=document.getElementById('numRes'),availDiv=document.getElementById('availableInputs'),procContainer=document.getElementById('processContainer'),runBtn=document.getElementById('runBtn'),genBtn=document.getElementById('generateBtn'),exBtn=document.getElementById('loadExampleBtn'),pauseBtn=document.getElementById('pauseBtn'),fwdBtn=document.getElementById('stepFwdBtn'),backBtn=document.getElementById('stepBackBtn'),resetBtn=document.getElementById('resetAnimBtn'),speedR=document.getElementById('speedRange'),timeline=document.getElementById('timeline'),canvas=document.getElementById('animCanvas'),stats=document.getElementById('stats'),resultMsg=document.getElementById('resultMessage');
let banker,animator=new Animator(canvas,stats);
function createInputs(P,R){availDiv.innerHTML='';procContainer.innerHTML='';const av=document.createElement('div');av.className='matrix-input';for(let j=0;j<R;j++){const i=document.createElement('input');i.type='number';i.value=Math.floor(Math.random()*4);av.appendChild(i);}availDiv.appendChild(av);
for(let p=0;p<P;p++){const box=document.createElement('div');box.className='process-box';const title=document.createElement('h4');title.textContent='P'+p;box.appendChild(title);const pair=document.createElement('div');pair.className='matrix-pair';const maxDiv=document.createElement('div');const allocDiv=document.createElement('div');maxDiv.className='matrix-input';allocDiv.className='matrix-input';for(let j=0;j<R;j++){const a=document.createElement('input');a.type='number';a.value=Math.floor(Math.random()*5);maxDiv.appendChild(a);const b=document.createElement('input');b.type='number';b.value=Math.floor(Math.random()*3);allocDiv.appendChild(b);}pair.appendChild(maxDiv);pair.appendChild(allocDiv);box.appendChild(document.createElement('small')).textContent='Max / Allocation';box.appendChild(pair);procContainer.appendChild(box);}}
function readMatrices(P,R){const av=[...availDiv.querySelectorAll('input')].map(x=>+x.value);const max=[],alloc=[];const boxes=[...procContainer.querySelectorAll('.process-box')];boxes.forEach(b=>{const ins=b.querySelectorAll('.matrix-pair div:first-child input');const ins2=b.querySelectorAll('.matrix-pair div:last-child input');max.push([...ins].map(x=>+x.value));alloc.push([...ins2].map(x=>+x.value));});return{av,max,alloc};}
genBtn.onclick=()=>createInputs(+numP.value,+numR.value);
exBtn.onclick=()=>{numP.value=5;numR.value=3;createInputs(5,3);const av=[3,3,2];availDiv.querySelectorAll('input').forEach((x,i)=>x.value=av[i]);const boxes=[...procContainer.querySelectorAll('.process-box')];const max=[[7,5,3],[3,2,2],[9,0,2],[2,2,2],[4,3,3]],alloc=[[0,1,0],[2,0,0],[3,0,2],[2,1,1],[0,0,2]];boxes.forEach((b,i)=>{b.querySelectorAll('.matrix-pair div:first-child input').forEach((x,j)=>x.value=max[i][j]);b.querySelectorAll('.matrix-pair div:last-child input').forEach((x,j)=>x.value=alloc[i][j]);});};
runBtn.onclick=()=>{const P=+numP.value,R=+numR.value;const {av,max,alloc}=readMatrices(P,R);banker=new Banker(av,max,alloc);const result=banker.run();animator.setTrace(result.trace);if(result.safe){resultMsg.textContent='✅ All processes completed successfully! Safe sequence: '+result.seq.map(i=>'P'+i).join(' → ');resultMsg.className='safe';}else{resultMsg.textContent='⚠️ Deadlock detected! Unsafe state reached.';resultMsg.className='deadlock';}};
fwdBtn.onclick=()=>animator.next();backBtn.onclick=()=>animator.prev();resetBtn.onclick=()=>{if(banker){banker.run();animator.setTrace(banker.trace);resultMsg.textContent='';}};
createInputs(5,3);
